### ISSUE TITLE
Names of a person (PersonInfo OMTD-SHARE 2.0.0)

### ISSUE THREAD

**Issue by reckart** [openminted/omtd-share_metadata_schema#1]
I don't understand how the PersonInfo works. It has `surnames`, `givennames` and `names`. I can understand that a person can have multiple names (e.g. a real name and an artist name), but I do wonder if the OMTD-SHARE schema needs to represent that. But ok, so there can be multiple names. 

But when using `surname` and `givenname`, how would one model which particular surname belongs to which given name?

I also don't understand why a name consists again of names. Cf. the following XML which was generated according to OMTD-SHARE 2.0.0:

```
    <contactPersons>
      <contactPersons>
        <surnames>
          <surnames>
            <surname>
              <surname>
                <value>Sumner</value>
                <lang>en</lang>
              </surname>
            </surname>
          </surnames>
        </surnames>
        <givenNames>
          <givenNames>
            <givenName>
              <givenName>
                <value>Gordon</value>
                <lang>en</lang>
              </givenName>
            </givenName>
          </givenNames>
          <givenNames>
            <givenName>
              <givenName>
                <value>Sting</value>
                <lang>en</lang>
              </givenName>
            </givenName>
          </givenNames>
        </givenNames>
        <names>
          <names>
            <name>
              <name>
                <value>Sumner, Gordon</value>
                <lang>en</lang>
              </name>
            </name>
          </names>
          <names>
            <name>
              <name>
                <value>Sting</value>
                <lang>en</lang>
              </name>
            </name>
          </names>
        </names>
      </contactPersons>
    </contactPersons>
```

I would have rather expected something like

```
    <contactPersons>
      <contactPersons>
        <name>Sumner, Gordon</name>
        <surname>Sumner</surname>
        <givenName>Gordon</givenName>
      </contactPersons>
    </contactPersons>
```

If it were really necessary to support multiple names or names in multiple languages, then maybe:

```
    <contactPersons>
      <contactPersons>
        <names>
          <name xml:lang="en">Sumner, Gordon</name>
          <name xml:lang="de">Sumner, Gordon</name>
          <name>Sting</name>
        </names>
        <compoundNames>
          <compoundName>
            <surname>Sumner</surname>
            <givenName>Gordon</givenName>
          </compoundName>
        </compoundNames>
      </contactPersons>
    </contactPersons>
```

**Comment by pennyl67** [comment]
Hi Richard!
In the XSD, you have a choice between surname+givenName and names - this
allows us to handle:
- common practice nowadays to ask for detailed person data (i.e. surname:
Summer, givenName: Gordon)
- the fact that in most cases of publications, in the author data there is
no distinction between givenName and surname (so we usually find "Summer,
Gordon" or "Gordon Summer" or "Summer Gordon").
In your example with the compound name, you presume that you already know
which is which, but that doesn't always happen.
Normally, with a choice from XSD, both choice elements should not be
generated; which tool have you used?
p

**Comment by reckart** [comment]
I have used the Java classes generated from the OMTD-SHARE 2.0.0 XSD which are provided by omtd-registry-api.

**Comment by reckart** [comment]
Ok, so let's assume I just know the name. Even then the XML seems to be more complex then necesssary:

```
        <names>
          <names>
            <name>
              <name>
                <value>Sumner, Gordon</value>
                <lang>en</lang>
              </name>
            </name>
          </names>
        </names>
```

There are two levels of "names" elements and then again two levels of "name" elements.

**Comment by pennyl67** [comment]
I don't know why this double level happens - maybe it has to do with the Java classes; in the XSD there's only one level. 
@courado can you check?

**Comment by reckart** [comment]
I may be using a wrong method to serialize the XML. I am using jackson and expected it would interpret the JAXB annotations - but I think I was wrong. I'll try a proper JAXB-based serialization.

**Comment by reckart** [comment]
Yep. After switching to proper JAXB-serializtion, it looks quite different ;)

**Comment by pennyl67** [comment]
Great! Shall we close the issue?

**Comment by reckart** [comment]
So I'm using "Willard Carroll Smith Jr." aka "Will Smith" as an example now - and I still don't understand the design. See this:

```
<ns1:contactInfo>
      <ns1:contactPersons>
        <ns1:contactPerson>
          <ns1:surnames>
            <ns1:surname>Smith</ns1:surname>
          </ns1:surnames>
          <ns1:surnames>
            <ns1:surname>Carroll</ns1:surname>
            <ns1:surname>Smith</ns1:surname>
            <ns1:surname>Jr.</ns1:surname>
          </ns1:surnames>
          <ns1:givenNames>
            <ns1:givenName>Will</ns1:givenName>
          </ns1:givenNames>
          <ns1:givenNames>
            <ns1:givenName>Willard</ns1:givenName>
          </ns1:givenNames>
          <ns1:names>
            <ns1:name>Smith, Will</ns1:name>
          </ns1:names>
          <ns1:names>
            <ns1:name>Carroll Smith Jr., Willard</ns1:name>
          </ns1:names>
        </ns1:contactPerson>
      </ns1:contactPersons>
    </ns1:contactInfo>
```

I can represent that the person has two names, but there is no way to tell which given name belongs to which surname. And the above is only one way of modelling it... there is e.g. also this way:

```
         <ns1:names>
            <ns1:name>Smith</ns1:name>
            <ns1:name>Will</ns1:name>
          </ns1:names>
          <ns1:names>
            <ns1:name>Carroll</ns1:name>
            <ns1:name>Smith</ns1:name>
            <ns1:name>Jr.</ns1:name>
            <ns1:name>Willard</ns1:name>
          </ns1:names>
```

IMHO either surname and given name would need to be grouped under a third element to ensure that one knows which belongs to which or we assume that every person only has a single name, but then it doesn't make sense to allow for multiple names. 

I also don't understand why both "names" and "name" are allowed multiple times. How is one supposed to use them? The example in the docu says

> The full name of a person; the preferred format is "family name, given name"

Then in my opinion it would make sense to allow for a single "names" element with multiple "name" elements in it:

```
          <ns1:names>
            <ns1:name>Smith, Will</ns1:name>
            <ns1:name>Carroll Smith Jr., Willard</ns1:name>
          </ns1:names>
```

So I am still confused ;)

**Comment by pennyl67** [comment]
The model lacks a lot as far as describing persons is concerned; if we really wanted to describe person data in full detail, we would use a similar approach to what you're describing, including more information (e.g. title, pseudonym, initials, middle name  etc.). However, the focus of the schema is on (language) resources; persons are described as satellite entities that are important, for instance, for attributing/citing purposes, as contact persons etc. 
In my view, persons (and all satellite entities) should be described somewhere else and we only get their data from a link to that registry; in our case, given that we mostly talk about researchers, the ORCID or any such authority list. But this can only be recommended and not enforced.
So, for now, the idea is to 
- have "surname" & "given name" as the only two fields for persons, where they put in "surname" all their surnames (e.g. Caroll Smith Jr.) and all names in "given name" (e.g. Willard); the fact that the same person has an alias name is not recorded in the model. And the reason we have multiple surnames and given names is because they are multilingual fields (e.g. Λαμπροπούλου in Greek and Labropoulou in English - or in the Latin script, as it should be more correctly documented). 
- have the "name" used mainly for cases that come from legacy data, especially for publications where author data is usually just one field; even the recommendation with the comma and inverse order (coming from OpenAIRE) is not always followed.
This seems to be the practice for the time being, cf. DataCite or the new OpenAIRE schema.

**Comment by reckart** [comment]
Ok, but then we don't need to allow multiple "names" elements. A single "names" element with multiple "name" elements inside it (one per language) would be entirely sufficient.

**Comment by pennyl67** [comment]
Could this be again due to the serialization? In the XSD, there's a single "names" element with multiple "name" elements and a rule for checking uniqueness per language.

**Comment by reckart** [comment]
It's not a matter of the serialization - but if could be a matter of the Java classes generated from the XSD. I don't know. You are right, when I look at the XSD, it doesn't seem as if multiple "names" elements should be allowed. Maybe @courado can say something about it.

**Comment by courado** [comment]
OK I have been looking for this problem, and it is a problem of the xsd->java plugin.
A simple fix that I test and will work is to group surnames and given names in a new element (separateNames) in this case, for example: 

```xsd
<xs:element name="separateNames">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="surnames">
				<xs:complexType>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" name="surname">
							[...]
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element minOccurs="0" name="givenNames">
				<xs:complexType>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" minOccurs="0" name="givenName">
							[...]
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
```

**Comment by pennyl67** [comment]
Ok, it looks reasonable; I'll change also in the XSD.

**Comment by courado** [comment]
Updated omtd-registry-api with the changes in version 2.0.1-SNAPSHOT

**Comment by reckart** [comment]
I have updated to the 2.0.1-SNAPSHOT now and generated the following XML:

```
      <ns1:contactPersons>
        <ns1:contactPerson>
          <ns1:separateNames>
            <ns1:surnames>
              <ns1:surname>Smith</ns1:surname>
              <ns1:surname>Carroll Smith Jr.</ns1:surname>
            </ns1:surnames>
            <ns1:givenNames>
              <ns1:givenName>Will</ns1:givenName>
              <ns1:givenName>Willard</ns1:givenName>
            </ns1:givenNames>
          </ns1:separateNames>
          <ns1:names>
            <ns1:name>Smith, Will</ns1:name>
            <ns1:name>Carroll Smith Jr., Willard</ns1:name>
          </ns1:names>
        </ns1:contactPerson>
      </ns1:contactPersons>
```

With the new API/XSD, it is possible to add multiple names for a person. However, it is not possible to add multiple separate names for a person, because it is not possible to know which given names and surnames belong to each other. This seems to be inconsistent. IMHO we can either allow only a single `name` which would also imply the given names and surnames always belong together - or we need to allow multiple `separateNames`, e.g. by intruducing a `separateName` element:

```
      <ns1:contactPersons>
        <ns1:contactPerson>
          <ns1:separateNames>
            <ns1:separateName>
              <ns1:givenNames>
                <ns1:givenName>Will</ns1:givenName>
              </ns1:givenNames>
              <ns1:surnames>
                <ns1:surname>Smith</ns1:surname>
              </ns1:surnames>
            </ns1:separateName>
            <ns1:separateName>
              <ns1:givenNames>
                <ns1:givenName>Willard</ns1:givenName>
              </ns1:givenNames>
              <ns1:surnames>
                <ns1:surname>Carroll</ns1:surname>
                <ns1:surname>Smith</ns1:surname>
                <ns1:surname>Jr.</ns1:surname>
                <!-- or should it be just one surname with "Carroll Smith Jr."? -->
              </ns1:surnames>
            </ns1:separateName>
          </ns1:separateNames>
          <ns1:names>
            <ns1:name>Smith, Will</ns1:name>
            <ns1:name>Carroll Smith Jr., Willard</ns1:name>
          </ns1:names>
        </ns1:contactPerson>
      </ns1:contactPersons>
```

**Comment by pennyl67** [comment]
The only reason for having surnames & givenNames as unbounded is that they are multilingual strings, and they should be unique per language. Which means that, for instance, "Eckart de Castilho" would be all in one element. Now, I've seen that the uniqueness constraint for the "lang" attribute doesn't work, and I have no time to check it now. 
If we go on having multiple elements, adding a "separateName" element is more correct theoretically; however, it adds one more wrapper element and, thus, more complexity. 
The other way would be to change the cardinality of names to max=1, which is not the best.
Can we leave as is for now and I'll check for the next release?

**Comment by reckart** [comment]
Sound ok to me. Might be useful to add a note to the documentation that not multiple names are allowed, only a single name in different languages/transliterations.
